# 连接数据源
spring:
  # 数据源配置，请修改为你项目的实际配置
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://10.82.26.150:1433;DatabaseName=master
    username: sa
    password: Password@

#  datasource:
#    username: root
#    password: ENC(aXcmM77CmYgj67mBxQgI2A==)
#    url: jdbc:mysql://ENC(oeR8yn+SoZCW3LJ/0vLC7i3EV4m5Dqq2):ENC(kUag3DtSAHXfncq/A1pQrg==)/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  redis:
    port: 6379
    host: ENC(0tz0hFsHtYzDUAHn2vcGQSLqqD3y+uN+)
    password: ENC(NVs/8etYI0sBoRKPG46mCeDZNgKVhAnt)
    database: 0
    connect-timeout: 2000


server:
  port: 8080

jasypt:
  encryptor:
    password: keafmd

# mybatis-plus
mybatis-plus:
  mapper-locations: com.keafmd.springdemo.mapper.*.xml








enterprise:
  tianyan:
    token: 5d9aba21-4903-4bc8-b3b7-f9f51a151493
    url: http://open.api.tianyancha.com/services/open/ic/baseinfo/normal?keyword=
    allUrl: http://open.api.tianyancha.com/services/open/ic/baseinfoV2/2.0?keyword=