# 连接数据源
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://114.115.148.110:4306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  redis:
    port: 6379
    host: 101.42.104.99
    password: 18044229
    database: 0
    connect-timeout: 2000


server:
  port: 8080



# mybatis-plus
mybatis-plus:
  mapper-locations: com.keafmd.springdemo.mapper.*.xml


enterprise:
  tianyan:
    token: 5d9aba21-4903-4bc8-b3b7-f9f51a151493
    url: http://open.api.tianyancha.com/services/open/ic/baseinfo/normal?keyword=
    allUrl: http://open.api.tianyancha.com/services/open/ic/baseinfoV2/2.0?keyword=